version: '3.1'
services:
    zoneminder:
        # Need to build image to enable GPU acceleration
        #image: dlandon/zoneminder.machine.learning:latest
        build:
            dockerfile: Dockerfile.build
            context: .
        container_name: zoneminder
        restart: unless-stopped
        ports:
            - 8443:443/tcp
            - 9000:9000/tcp
        runtime: nvidia
        network_mode: "bridge"
        privileged: true
        shm_size: "8gb"
        environment:
            - TZ=America/New_York
            - PUID=99
            - PGID=100
            - MULTI_PORT_START=0
            - MULTI_PORT_END=0
        volumes:
            - /dev/v4l:/dev/v4l
            - zoneminder_config:/config:rw
            - zoneminder_data:/var/cache/zoneminder:rw
            - /usr/local/cuda:/usr/local/cuda
        # We're using privileged mode.  Uncomment and configure if not
        #devices:
        #    - "/dev/dri:/dev/dri"
        #    - "/dev/nvidia0:/dev/nvidia0"
        #    - "/dev/nvidiactl:/dev/nvidiactl"
        #    - "/dev/nvidia-modeset:/dev/nvidia-modeset"
        #    - "/dev/nvidia-uvm:/dev/nvidia-uvm"
        #    - "/dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools"
        #    - "/dev/video0:/dev/video0" 
volumes:
    zoneminder_config:
    zoneminder_data:
