version: '3.1'
services:
    zoneminder:
        build:
            dockerfile: Dockerfile.build
            context: .
        container_name: zoneminder
        #image: dlandon/zoneminder.machine.learning:latest
        restart: unless-stopped
        ports:
            - 8443:443/tcp
            - 9000:9000/tcp
        runtime: nvidia
        network_mode: "bridge"
        privileged: true
        shm_size: "8gb"
        environment:
            - TZ=America/New_York
            - PUID=99
            - PGID=100
            - MULTI_PORT_START=0
            - MULTI_PORT_END=0
        volumes:
            - /dev/v4l:/dev/v4l
            - zoneminder_config:/config:rw
            - zoneminder_data:/var/cache/zoneminder:rw
            - /usr/local/cuda:/usr/local/cuda
volumes:
    zoneminder_config:
    zoneminder_data:
